### ISSUE TITLE
bot error while making it online

### ISSUE THREAD

**Issue by ELECTROISLIVE** [cluzier/treehouse-bot#10]
internal/modules/cjs/loader.js:896
  throw err;
  ^

Error: Cannot find module '../build/Release/canvas.node'
Require stack:
- C:\Users\HP\Desktop\treehouse-bot-master\node_modules\canvas\lib\bindings.js
- C:\Users\HP\Desktop\treehouse-bot-master\node_modules\canvas\lib\canvas.js
- C:\Users\HP\Desktop\treehouse-bot-master\node_modules\canvas\index.js
- C:\Users\HP\Desktop\treehouse-bot-master\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:893:15)
    at Function.Module._load (internal/modules/cjs/loader.js:743:27)
    at Module.require (internal/modules/cjs/loader.js:965:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\HP\Desktop\treehouse-bot-master\node_modules\canvas\lib\bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Module.require (internal/modules/cjs/loader.js:965:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\HP\\Desktop\\treehouse-bot-master\\node_modules\\canvas\\lib\\bindings.js',
    'C:\\Users\\HP\\Desktop\\treehouse-bot-master\\node_modules\\canvas\\lib\\canvas.js',
    'C:\\Users\\HP\\Desktop\\treehouse-bot-master\\node_modules\\canvas\\index.js',
    'C:\\Users\\HP\\Desktop\\treehouse-bot-master\\index.js'
  ]

@cluzier how to fix this

**Comment by ghost** [comment]
Try doing the following commands;
`npm uninstall canvas`
 `npm install canvas`
