### ISSUE TITLE
when i run node index.js in parrot sec os , i am getting like this , what to do 

### ISSUE THREAD

**Issue by the-darklord** [cluzier/treehouse-bot#8]
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module '../build/Release/canvas.node'
Require stack:
- /home/saimihirnath/treehouse-bot/node_modules/canvas/lib/bindings.js
- /home/saimihirnath/treehouse-bot/node_modules/canvas/lib/canvas.js
- /home/saimihirnath/treehouse-bot/node_modules/canvas/index.js
- /home/saimihirnath/treehouse-bot/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/saimihirnath/treehouse-bot/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/saimihirnath/treehouse-bot/node_modules/canvas/lib/bindings.js',
    '/home/saimihirnath/treehouse-bot/node_modules/canvas/lib/canvas.js',
    '/home/saimihirnath/treehouse-bot/node_modules/canvas/index.js',
    '/home/saimihirnath/treehouse-bot/index.js'
  ]
}

**Comment by Arisamiga** [comment]
> * canvas

I suggest you reinstall the Canva module By doing the following on a command line.

``` 
npm uninstall canvas
npm install canvas
```
